### ISSUE TITLE
How is this library different from EntityX, what are the use cases where it is preferable?

### ISSUE THREAD

**Issue by sztomi** [miguelmartin75/anax#42]
I'm looking for a Component-Entity-System library, and I found these two. The faq lists EntityX as an inspiration. I find the two very similar in goals and implementation as well. Is there a killer advantage to choose either?

**Comment by LearnCocos2D** [comment]
"Here are some major differences:"

You may want to rephrase that as it's not clear whether this list is about features that are in entityX but not in anax or vice versa, especially since some items in the list are "pros" and others are "cons".

PS: I intend to benchmark anax, entityx and artemiscpp next week as I need an ECS in TilemapKit. I'll post an update with a link to the blog post when I'm done. I'm curious to see how the libraries compare.

**Comment by skyrpex** [comment]
did you finally created those benchmarks?

**Comment by dzanis** [comment]
I did a test. Created 100,000 entities (SFML) .FPS the same, but the difference in memory usage.Anax uses more memory. 
![anax_test_2016-10-30_11-43-00](https://cloud.githubusercontent.com/assets/5854040/19835682/ab08e2ce-9e96-11e6-9c79-a64c6456f5e7.png)
![entityx_test](https://cloud.githubusercontent.com/assets/5854040/19835684/b2bf195c-9e96-11e6-89e8-64f790b6a068.png)
