### ISSUE TITLE
Possible data race

### ISSUE THREAD

**Issue by miguelmartin75** [miguelmartin75/anax#55]
`ClassTypeId` has a possible data-race. e.g.

Thread 1:

``` c++
ClassTypeId<A>::GetTypeId<B>();
```

Thread 2:

``` c++
ClassTypeId<A>::GetTypeId<C>();
```

I am not sure what will occur. I am not sure if the `m_nextTypeId` will be appropriately incremented (I doubt it).

**Comment by EarthlingKira** [comment]
After reviewing the code (btw, good work, nice ECS implementation) I found this issue and wanted to report it here, I am pretty sure this is a data race and may lead to two types having the same ID, although the probability is low since this can only happen when the type is ID'd for the first time.

See here for more info: https://stackoverflow.com/a/3673248

I created a pull request for the most simple fix there is since C++11, simply using an atomic (arithmetic operators like ++ are overloaded)
