### ISSUE TITLE
Version 2.0.0

### ISSUE THREAD

**Issue by ninnghazad** [miguelmartin75/anax#58]
"getComponent/addComponent/etc. now return a pointer"
Arg... that would mean hundreds of changes in multiple dozens of files across C++ and script. Only so i could dereference all those pointers to references or whatever. Why not a getComponentPtr additionally?
Could you elaborate a bit on the topic? Also you wrote you might change it back - so i'm kind of hesitant to update anax. 

Edit: By elaborate i mean, what do we get from that change? What's that wrapper, and what could we use it for?

**Comment by miguelmartin75** [comment]
I figured someone would be annoyed by this change. I might change it back to be quite honest. It was mainly there so I could make a ComponentPtr wrapper that would be used to store where the component is via an index. So that way, if I was to store them contiguously, the 'fake' pointers would never be invalidated if you were to move where they are located in memory. However, at the moment, I haven't even written the code for this.

**Comment by miguelmartin75** [comment]
I modified the master branch to use [references](https://github.com/miguelmartin75/anax/tree/references).
