### ISSUE TITLE
How to get array/vector of smart-pointers-to-components of an entity?

### ISSUE THREAD

**Issue by ninnghazad** [miguelmartin75/anax#65]
I want to try to de/serialize using RTTI, for that i would need to get all components of an entity as smart pointers. 
However getComponents() returns raw pointers, though i see smart pointers being used internally - is there a way to get them?
I don't want to have pages long spaghetti functions checking/serializing each type of component explicitly, 
instead i want to do something like this:

    serialize(entities.size());
    for(auto & e : entities) {
        auto components = e.getComponents();
        serialize(components.size());
        for(auto & c : components) {
            serialize(c);
        }
    }

am i missing something? anybody has ideas how to get there?
(the serialize() handles polymorphism as long as i can pass it smart ptrs)

**Comment by miguelmartin75** [comment]
Components are stored as unique_ptr's. You can't access the unique_ptr, unless you want to modify the code, but I don't really see a reason to do this. Even if you construct another unique_ptr or shared_ptr, you'll end up double deleting in your program.

The real question is: Why do you need to pass it as a smart pointer rather than a raw pointer? You don't need smart pointers for RTTI.

Also, instead of RTTI, you could map the component type (which is an integer) to a function that serialises that component. Unfortunately, I don't have this built-in, as I don't require to use CRTP anymore. So, how I would do this is:

```c++
struct MyComponentBase : Component 
{
     using TypeId = anax::detail::TypeId;
      virtual TypeId typeId() const = 0; 
};
template <class T>
struct MyComponent : MyComponentBase
{
     virtual TypeId typeId() const { return anax::ComponentTypeId<T>(); } 
};

// ...
std::map<TypeId, std::function<void (anax::Component*)>> serialiseFns;
serialize(entities.size());
for(auto & e : entities) {
    auto components = e.getComponents();
    serialize(components.size());
    for(auto & c : components) {
        serialiseFns[static_cast<MyComponentBase*>(c)->typeId()](c);
    }
} 
```

Alternatively instead of the map, just put another virtual function in the base class called serialise (in this case no need for typeId for serialization, but you will to read your serialized data [to map to ctors]). 

This is quite a hacky work-around, but it works. There might be a cleaner way, I just thought of this off the top of my head though. Note: this is if you don't want to use RTTI (or rather implement RTTI for yourself, which may or may not be faster).

**Comment by ninnghazad** [comment]
Almost forgot to check back in. After thinking about your response and lots of trying i came up with a nice registry for component-types that i can use to generate de/serialization functions and apply them.
Was a bit complicated to write, but easy to use and no changes to libaries involved.
It's not perfect yet, but works so far. Thanks.
